color:
  brandStrength: 0.5
  saturation: 0.25
  brandColors:
    - '#000000'
    - '#e8e7ec'
    - '#1e262a'
    - '#b29f93'
    - '#6b574c'
  lightness: 0.25
  rhythmicContrast: 0.5
title: Christian Schumann - conductor - composer - instrumentalist
analytics:
  twitter: null
  google: UA-73138904-1
  facebook: null
collections:
  - index:
      paginate: true
      path: /
      number: 15
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      format: rss
      path: /rss.xml
      number: 10
cta:
  version: null
  bucket: null
  domain: null
favicon: null
layout_spectrum: 1
purpose: []
name: Christian Schumann
opengraph:
  image: null
  type: null
  appId: null
typography_spectrum: 0.59752
