name: Christian Schumann
favicon: null
layout_spectrum: 0.7436
typography_spectrum: 0.57327
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
title: Christian Schumann - Conductor / Composer / Instrumentalist
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#03113a'
    - '#fefdde'
    - '#2b6499'
    - '#3e9ec7'
    - '#f6cd9b'
  brandStrength: 0.75
  lightness: 0.6875
  saturation: 0.7930668
  rhythmicContrast: 0.5
purpose: []
