name: Christian Schumann
favicon: null
layout_spectrum: 1
typography_spectrum: 0.59752
title: Christian Schumann - conductor - composer - instrumentalist
collections:
  - index:
      paginate: true
      path: /
      number: 15
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      format: rss
      path: /rss.xml
      number: 10
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: UA-73138904-1
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#e8e7ec'
    - '#1e262a'
    - '#b29f93'
    - '#6b574c'
  brandStrength: 0.5
  lightness: 0.25
  saturation: 0.25
  rhythmicContrast: 0.5
purpose: []
