typography_spectrum: 0.59752
color:
  brandColors:
    - '#000000'
    - '#e8e7ec'
    - '#1e262a'
    - '#b29f93'
    - '#6b574c'
  brandStrength: 0.5
  lightness: 0.25
  saturation: 0.25
  rhythmicContrast: 0.5
opengraph:
  image: null
  type: 'https://www.facebook.com/ChristianSchumannOfficial/'
  appId: null
layout_spectrum: 1
analytics:
  google: UA-73138904-1
  facebook: null
  twitter: null
author:
  name: Christian Schumann
  email: contact@christian-schumann.com
  url: 'http://christian-schumann.com/'
name: Christian Schumann
cta:
  domain: null
  bucket: null
  version: null
favicon: null
collections:
  - index:
      paginate: true
      path: /
      number: 15
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      format: rss
      path: /rss.xml
      number: 10
title: Christian Schumann
description: conductor - composer
purpose: []
