name: Christian Schumann
favicon: null
layout_spectrum: 0.5458892
typography_spectrum: 0.7091063
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
title: Christian Schumann - Conductor/Composer/Instrumentalist
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#020E39'
    - '#1F305C'
    - '#FDFEDD'
    - '#208091'
    - '#77ABB3'
  brandStrength: 0.8668316
  lightness: 0.8025976
  saturation: 0.7930668
  rhythmicContrast: 0.09862733
purpose: []
