name: Christian Schumann
favicon: null
layout_spectrum: 1
typography_spectrum: 0.51817
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
title: Christian Schumann
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: UA-73138904-1
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#00042a'
    - '#ffffdd'
    - '#016773'
    - '#2985a9'
    - '#aa9c82'
  brandStrength: 0.3125
  lightness: 0.5625
  saturation: 0.1875
  rhythmicContrast: 0.5
purpose: []
