layout_spectrum: 0.5458892
typography_spectrum: 0.6439795
color:
  saturation: 0.7930668
  lightness: 0.8025976
  brandStrength: 0.8668316
  rhythmicContrast: 0.09862733
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
name: Christian Schumann
