name: Christian Schumann
favicon: null
layout_spectrum: 0
typography_spectrum: 0.51211
title: 'Christian Schumann   -   c & c'
collections:
  - index:
      paginate: true
      path: /
      number: 15
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      format: rss
      path: /rss.xml
      number: 10
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: UA-73138904-1
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#00042a'
    - '#ffffdd'
    - '#016773'
    - '#2985a9'
    - '#aa9c82'
  brandStrength: 0.8125
  lightness: 0.4375
  saturation: 0.1875
  rhythmicContrast: 0.5
purpose: []
