collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
color:
  saturation: 0.7930668
  brandStrength: 0.8668316
  lightness: 0.8025976
  brandColors:
    - '#020E39'
    - '#1F305C'
    - '#FDFEDD'
    - '#208091'
    - '#77ABB3'
  rhythmicContrast: 0.09862733
typography_spectrum: 0.7091063
layout_spectrum: 0.5458892
name: Christian Schumann
